version: 2.1

workflows:
  show-env-vars:
    jobs:
      - show-env

jobs:
  show-env:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $MY_ENV_VAR
