version: 2.1

commands: 
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

workflows:
  test-commands:
    jobs:
      - commands_test

jobs:
  commands_test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - print_pipeline_id
